// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_LostConnectionBox = NULL;
lv_obj_t * ui_LostConnectionText = NULL;
lv_obj_t * ui_Unplugged = NULL;
// event funtions
void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_Connect_screen_init(void)
{
    ui_Connect = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LostConnectionBox = lv_obj_create(ui_Connect);
    lv_obj_set_width(ui_LostConnectionBox, 237);
    lv_obj_set_height(ui_LostConnectionBox, 50);
    lv_obj_set_x(ui_LostConnectionBox, 0);
    lv_obj_set_y(ui_LostConnectionBox, 30);
    lv_obj_set_align(ui_LostConnectionBox, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LostConnectionBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LostConnectionBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LostConnectionBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LostConnectionBox, lv_color_hex(0xCF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LostConnectionBox, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LostConnectionBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LostConnectionBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LostConnectionBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LostConnectionBox, lv_color_hex(0xCF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LostConnectionBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LostConnectionBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LostConnectionBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_LostConnectionBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_LostConnectionBox, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LostConnectionText = lv_label_create(ui_LostConnectionBox);
    lv_obj_set_width(ui_LostConnectionText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LostConnectionText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LostConnectionText, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LostConnectionText, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LostConnectionText, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LostConnectionText, "Please connect the controller");
    lv_obj_set_style_text_color(ui_LostConnectionText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LostConnectionText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Unplugged = lv_image_create(ui_Connect);
    lv_image_set_src(ui_Unplugged, &ui_img_unplugged_png);
    lv_obj_set_width(ui_Unplugged, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Unplugged, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Unplugged, 0);
    lv_obj_set_y(ui_Unplugged, -40);
    lv_obj_set_align(ui_Unplugged, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Unplugged, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Unplugged, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);

}

void ui_Connect_screen_destroy(void)
{
    if(ui_Connect) lv_obj_del(ui_Connect);

    // NULL screen variables
    ui_Connect = NULL;
    ui_LostConnectionBox = NULL;
    ui_LostConnectionText = NULL;
    ui_Unplugged = NULL;

}
