// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_CONNECT_H
#define UI_CONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connect
extern void ui_Connect_screen_init(void);
extern void ui_Connect_screen_destroy(void);
extern void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_LostConnectionBox;
extern lv_obj_t * ui_LostConnectionText;
extern lv_obj_t * ui_Unplugged;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

