// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Loading = NULL;
lv_obj_t * ui_LoadingContainer = NULL;
lv_obj_t * ui_LoadingBar = NULL;
lv_obj_t * ui_LoadingText = NULL;
// event funtions

// build funtions

void ui_Loading_screen_init(void)
{
    ui_Loading = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingContainer = lv_obj_create(ui_Loading);
    lv_obj_remove_style_all(ui_LoadingContainer);
    lv_obj_set_width(ui_LoadingContainer, 249);
    lv_obj_set_height(ui_LoadingContainer, 50);
    lv_obj_set_x(ui_LoadingContainer, -2);
    lv_obj_set_y(ui_LoadingContainer, 88);
    lv_obj_set_align(ui_LoadingContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LoadingContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoadingBar = lv_bar_create(ui_LoadingContainer);
    lv_bar_set_value(ui_LoadingBar, 500, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LoadingBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LoadingBar, 230);
    lv_obj_set_height(ui_LoadingBar, 16);
    lv_obj_set_x(ui_LoadingBar, 0);
    lv_obj_set_y(ui_LoadingBar, 15);
    lv_obj_set_align(ui_LoadingBar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LoadingBar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LoadingBar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_LoadingBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoadingBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LoadingBar, lv_color_hex(0xA40000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LoadingBar, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LoadingBar, lv_color_hex(0xA40000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LoadingBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LoadingBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LoadingBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_LoadingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_LoadingBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LoadingBar, lv_color_hex(0x004160), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LoadingBar, lv_color_hex(0x00E3FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LoadingBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LoadingBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LoadingBar,
                                                                                                 lv_obj_get_style_pad_right(ui_LoadingBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LoadingText = lv_label_create(ui_LoadingContainer);
    lv_obj_set_width(ui_LoadingText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoadingText, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LoadingText, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LoadingText, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LoadingText, "LOADING");
    lv_obj_set_style_text_color(ui_LoadingText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadingText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Loading_screen_destroy(void)
{
    if(ui_Loading) lv_obj_del(ui_Loading);

    // NULL screen variables
    ui_Loading = NULL;
    ui_LoadingContainer = NULL;
    ui_LoadingBar = NULL;
    ui_LoadingText = NULL;

}
