// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_LOADING_H
#define UI_LOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Loading
extern void ui_Loading_screen_init(void);
extern void ui_Loading_screen_destroy(void);
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_LoadingContainer;
extern lv_obj_t * ui_LoadingBar;
extern lv_obj_t * ui_LoadingText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

