// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern void ui_event_Menu(lv_event_t * e);
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Control;
extern lv_obj_t * ui_SpeedBarUp;
extern lv_obj_t * ui_SpeedBarDown;
extern lv_obj_t * ui_SpeedBarRight;
extern lv_obj_t * ui_SpeedBarLeft;
extern lv_obj_t * ui_Extras;
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_AboutContainer;
extern lv_obj_t * ui_AboutTitle;
extern lv_obj_t * ui_AboutText;
extern lv_obj_t * ui_BatteryBox;
extern lv_obj_t * ui_BatteryImage;
extern lv_obj_t * ui_BatteryText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

