// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_Control = NULL;
lv_obj_t * ui_SpeedBarUp = NULL;
lv_obj_t * ui_SpeedBarDown = NULL;
lv_obj_t * ui_SpeedBarRight = NULL;
lv_obj_t * ui_SpeedBarLeft = NULL;
lv_obj_t * ui_Extras = NULL;
lv_obj_t * ui_About = NULL;
lv_obj_t * ui_AboutContainer = NULL;
lv_obj_t * ui_AboutTitle = NULL;
lv_obj_t * ui_AboutText = NULL;
lv_obj_t * ui_BatteryBox = NULL;
lv_obj_t * ui_BatteryImage = NULL;
lv_obj_t * ui_BatteryText = NULL;
// event funtions
void ui_event_Menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_Connect, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Connect_screen_init);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Menu);
    lv_tabview_set_tab_bar_position(ui_TabView1, LV_DIR_LEFT);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 240);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TabView1, lv_color_hex(0x930000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TabView1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TabView1, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TabView1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_bar(ui_TabView1), LV_TEXT_ALIGN_LEFT,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xA40000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(lv_tabview_get_tab_bar(ui_TabView1), LV_GRAD_DIR_HOR,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_tabview_get_tab_bar(ui_TabView1), LV_TEXT_ALIGN_AUTO,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(lv_tabview_get_tab_bar(ui_TabView1), LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Control = lv_tabview_add_tab(ui_TabView1, "Control");

    ui_SpeedBarUp = lv_bar_create(ui_Control);
    lv_bar_set_value(ui_SpeedBarUp, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBarUp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBarUp, 82);
    lv_obj_set_height(ui_SpeedBarUp, 30);
    lv_obj_set_x(ui_SpeedBarUp, 42);
    lv_obj_set_y(ui_SpeedBarUp, 31);
    lv_obj_set_align(ui_SpeedBarUp, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBarUp, lv_color_hex(0xC7C7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SpeedBarUp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SpeedBarUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBarUp, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SpeedBarUp, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBarUp, lv_color_hex(0x18BA00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarUp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SpeedBarUp, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SpeedBarUp,
                                                                                                 lv_obj_get_style_pad_right(ui_SpeedBarUp, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SpeedBarDown = lv_bar_create(ui_Control);
    lv_bar_set_value(ui_SpeedBarDown, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBarDown, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBarDown, 82);
    lv_obj_set_height(ui_SpeedBarDown, 30);
    lv_obj_set_x(ui_SpeedBarDown, 72);
    lv_obj_set_y(ui_SpeedBarDown, 37);
    lv_obj_set_align(ui_SpeedBarDown, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBarDown, lv_color_hex(0xC7C7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SpeedBarDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SpeedBarDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBarDown, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SpeedBarDown, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBarDown, lv_color_hex(0xA90000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarDown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SpeedBarDown, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SpeedBarDown,
                                                                                                   lv_obj_get_style_pad_right(ui_SpeedBarDown, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SpeedBarRight = lv_bar_create(ui_Control);
    lv_bar_set_value(ui_SpeedBarRight, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBarRight, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBarRight, 82);
    lv_obj_set_height(ui_SpeedBarRight, 30);
    lv_obj_set_x(ui_SpeedBarRight, 73);
    lv_obj_set_y(ui_SpeedBarRight, 19);
    lv_obj_set_align(ui_SpeedBarRight, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBarRight, lv_color_hex(0xC7C7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SpeedBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SpeedBarRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBarRight, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SpeedBarRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBarRight, lv_color_hex(0xB9B700), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarRight, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SpeedBarRight, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SpeedBarRight,
                                                                                                    lv_obj_get_style_pad_right(ui_SpeedBarRight, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SpeedBarLeft = lv_bar_create(ui_Control);
    lv_bar_set_value(ui_SpeedBarLeft, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SpeedBarLeft, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeedBarLeft, 82);
    lv_obj_set_height(ui_SpeedBarLeft, 30);
    lv_obj_set_x(ui_SpeedBarLeft, 40);
    lv_obj_set_y(ui_SpeedBarLeft, 49);
    lv_obj_set_align(ui_SpeedBarLeft, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SpeedBarLeft, lv_color_hex(0xC7C7C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SpeedBarLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SpeedBarLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SpeedBarLeft, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SpeedBarLeft, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedBarLeft, lv_color_hex(0xB9B700), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedBarLeft, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SpeedBarLeft, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SpeedBarLeft,
                                                                                                   lv_obj_get_style_pad_right(ui_SpeedBarLeft, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Extras = lv_tabview_add_tab(ui_TabView1, "Extras");

    ui_About = lv_tabview_add_tab(ui_TabView1, "About");

    ui_AboutContainer = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_AboutContainer);
    lv_obj_set_width(ui_AboutContainer, 222);
    lv_obj_set_height(ui_AboutContainer, 193);
    lv_obj_set_x(ui_AboutContainer, -4);
    lv_obj_set_y(ui_AboutContainer, 15);
    lv_obj_set_align(ui_AboutContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AboutContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AboutTitle = lv_label_create(ui_AboutContainer);
    lv_obj_set_width(ui_AboutTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AboutTitle, 0);
    lv_obj_set_y(ui_AboutTitle, lv_pct(-45));
    lv_obj_set_align(ui_AboutTitle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutTitle, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AboutTitle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_AboutTitle, "Baitboat Software");
    lv_obj_set_style_text_align(ui_AboutTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_AboutTitle, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AboutTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutText = lv_label_create(ui_AboutContainer);
    lv_obj_set_width(ui_AboutText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutText, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutText, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_AboutText, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_AboutText,
                      "Version: 0.1V\n\nAuthor: Timefly Workshop\n\nLast Change Date: July 28, 2025\n\nDescription: A control application for a\nfishing boat with a graphical interface,\nenabling movement and navigation\ncontrol via joystick.\n");
    lv_obj_set_style_text_color(ui_AboutText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AboutText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AboutText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_AboutText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AboutText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBox = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_BatteryBox);
    lv_obj_set_width(ui_BatteryBox, 43);
    lv_obj_set_height(ui_BatteryBox, 52);
    lv_obj_set_x(ui_BatteryBox, -2);
    lv_obj_set_y(ui_BatteryBox, 2);
    lv_obj_set_align(ui_BatteryBox, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_BatteryBox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryImage = lv_image_create(ui_BatteryBox);
    lv_image_set_src(ui_BatteryImage, &ui_img_battery_battery1_png);
    lv_obj_set_width(ui_BatteryImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryImage, 1);
    lv_obj_set_y(ui_BatteryImage, 6);
    lv_obj_set_align(ui_BatteryImage, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryImage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryImage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_BatteryImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BatteryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BatteryImage, 200);

    ui_BatteryText = lv_label_create(ui_BatteryBox);
    lv_obj_set_width(ui_BatteryText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BatteryText, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_BatteryText, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BatteryText, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BatteryText, "100%");
    lv_obj_set_style_text_color(ui_BatteryText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Menu, ui_event_Menu, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_TabView1 = NULL;
    ui_Control = NULL;
    ui_SpeedBarUp = NULL;
    ui_SpeedBarDown = NULL;
    ui_SpeedBarRight = NULL;
    ui_SpeedBarLeft = NULL;
    ui_Extras = NULL;
    ui_About = NULL;
    ui_AboutContainer = NULL;
    ui_AboutTitle = NULL;
    ui_AboutText = NULL;
    ui_BatteryBox = NULL;
    ui_BatteryImage = NULL;
    ui_BatteryText = NULL;

}
